name: Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/checkout@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Use linter
        run: npm run lint
